version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  kubernetes: circleci/kubernetes@1.3.0
  helm: circleci/helm@2.0.0

commands:
  aws-oidc-setup:
    description: Setup AWS auth using OIDC token
    parameters:
      aws_role_arn:
        type: string
    steps:
      - run:
          name: Get short-term credentials
          command: |
            STS=($(aws sts assume-role-with-web-identity --role-arn << parameters.aws_role_arn >> --role-session-name "deploy" --web-identity-token "${CIRCLE_OIDC_TOKEN}" --duration-seconds 900 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --output text))
            echo "export AWS_ACCESS_KEY_ID=${STS[0]}" >> $BASH_ENV
            echo "export AWS_SECRET_ACCESS_KEY=${STS[1]}" >> $BASH_ENV
            echo "export AWS_SESSION_TOKEN=${STS[2]}" >> $BASH_ENV
      - run:
          name: Verify AWS credentials
          command: aws sts get-caller-identity

jobs:
  deploy:
    executor: aws-cli/default
    parameters:
      region:
        type: string
      cluster_name:
        type: string
    steps:
      - checkout
      - aws-cli/install
      - helm/install-helm-client:
          version: "v3.9.0"
      - aws-oidc-setup:
          aws_role_arn: arn:aws:iam::375433828430:role/k5a-adam-k8s
      - run:
          name: Connect to EKS Cluster
          command: aws eks --region << parameters.region >> update-kubeconfig --name << parameters.cluster_name >>
      - run:
          name: Helm deployment (dry-run)
          command: helm upgrade adam-k8s ./deployments/deploy-helm/adam-k8s
            --namespace adam-k8s
            --install --atomic --debug --timeout 4m
            --set domain=adam-k8s.k8s-staging.devguru.co
            --dry-run
      - run:
          name: Helm deployment
          command: helm upgrade adam-k8s ./deployments/deploy-helm/adam-k8s
            --namespace adam-k8s
            --install --atomic --debug --timeout 4m
            --set domain=adam-k8s.k8s-staging.devguru.co

workflows:
  build_and_deploy:
    jobs:
      - deploy:
          context: just_oidc
          region: eu-central-1
          cluster_name: kalluna