apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.app.service.name }}
  labels:
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  selector:
    app:  {{ .Values.app.name }}
  type:  {{ .Values.app.service.type }}
  ports:
  - name:  http
    port:  {{ .Values.app.service.port }}        # port exposed outside ClusterIP
    targetPort:  {{ .Values.app.port }} # port exposed by Pod